### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Thoughtscript** [Thoughtscript/cyber_threat_challenge#1]
- [ ]  API - Supporting National Vulnerability Database
- [ ] React - Map if you are visualizing geo-location data that can zoom in/out.
- [ ] React - Grid control (aka…a table of data) to present the data presented in the map.
- [ ] React - Search of data to change the presentation in the map and grid.
- [ ] Docker to Simplify Deployment
- [ ] Unit Tests 
- [ ] Integration Tests
